version: "3.7"
services:
  api:
    build: api
    image: car-n-api
    container_name: api
    ports:
      - "3000:80"
    volumes:
      - type: bind
        source: ./api/database.json
        target: /app/database.json
        read_only: false
  gui:
    build: gui
    image: car-n-gui
    container_name: gui
    ports:
      - "4200:80"
    depends_on:
      - api
